spring:
   application:
      name: service-config-server
   profiles:
      active: native #이걸 git으로 바꾸면 git에서 가져옴. native로 하면 native 설정 가져옴.

---
# configuration: common       
server:
   port: 7777

encrypt:
   key-store:
      alias: selfsigned
      location: classpath:keystore.jks
      password: password
    
    
---
# configuration: git
spring:
   config:
      activate:
         on-profile: git
   cloud:
      config:
         server:
            encrypt.enabled: true
            git:
               uri: https://github.com/leejw-lu/msa-practices-config-repo  #msa-practices-config-repo 레포지토리 단독이다.
               searchPaths: service-emaillist,
                            service-storage,
                            service-gallery,
                            service-guestbook,
                            service-gateway-server

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
               

---
# configuration: native(file system)
spring:
   config:
      activate:
         on-profile: native
   
   cloud:
     config:
       server:
          encrypt.enabled: false
          native:                  
              searchLocations: file:///D:/poscodx2024/sts-workspace/msa-practices-config-repo-main/service-emaillist,
                               file:///D:/poscodx2024/sts-workspace/msa-practices-config-repo/service-storage,
                               file:///D:/poscodx2024/sts-workspace/msa-practices-config-repo/service-gallery,
                               file:///D:/poscodx2024/sts-workspace/msa-practices-config-repo/service-guestbook,
                              file:///D:/poscodx2024/sts-workspace/msa-practices-config-repo/service-gateway-server

logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO